version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_host
    restart: always
    tty: true
    volumes:
      - ./export:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '8080:8080'
      - '15001:5001'