version: '3.9'

services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: always
    volumes:
      - $PWD/ql/config:/ql/config
      - $PWD/ql/log:/ql/log
      - $PWD/ql/db:/ql/db
      - $PWD/ql/scripts:/ql/scripts
    tty: true
    ports:
      - "127.0.0.1:5700:5700"