version: '3'

services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    restart: always
    tty: true
    volumes:
      - ./data:/data
    ports:
      - '3000:3000'
      - '3000:3000/udp'
      - '22027:22027'
      - '22027:22027/udp'
      - '22037:22037'
      - '22037:22037/udp'
      - '22330:22330'
      - '22330:22330/udp'    
      - '18886:8886'